name = "Anish Bonda"
rol = "Student"
email = "bondaanish2@gmail.com"
phone = "+91 971521119"
birthday = "June 20, 2005"
location = "Bhimavaram, Andhra Pradesh, India"
avatar = "./config/assets/avatars/avatar-my.png"
username = "20thLionKings" # <-- github user name
googlemaps = "https://www.google.com/maps/place/Bhimavaram,+Andhra+Pradesh/@16.5432685,81.4749412,13z/data=!3m1!4b1!4m6!3m5!1s0x3a37d2a6a86d3e4b:0x4eed21243d2dcfed!8m2!3d16.544893!4d81.521241!16zL20vMDdfdDU2?entry=ttu" 
presentation = """
I'm a student currently pursuing Btech in Computer Science and Engineering. I enjoy turning complex problems into simple, beautiful and intuitive designs.
"""
