[my]
name = "Ivan Huamani"
rol = "Flutter Developer"
email = "saul@example.com"
phone = "+1 (213) 352-2795"
birthday = "June 26, 1996"
location = "Sacramento, California, USA"
avatar = "./assets/images/my-avatar.png"

# https://ionic.io/ionicons
[social]
facebook = "https://facebook.com/"
twitter = "https://twitter.com/"
instagram = "https://instagram.com/"
github = "https://github.com/ivansaul"

[about]
presentation = """
I'm Creative Director and UI/UX Designer from Sydney, Australia, working in web development and print media. I enjoy turning complex problems into simple, beautiful and intuitive designs.

My job is to build your website so that it is functional and user-friendly but at the same time attractive. Moreover, I add personal touch to your product and make sure that is eye-catching and easy to use. My aim is to bring across your message and identity in the most creative way. I created web design for many famous brand companies.
"""
