[my]
name = "Ivan Huamani"
rol = "Flutter Developer"
email = "email@example.com"
phone = "+1 (213) 352-2795"
birthday = "June 26, 1996"
location = "Sacramento, California, USA"
avatar = "./config/assets/avatars/my-avatar.png"
presentation = """
I'm Creative Director and UI/UX Designer from Sydney, Australia, working in web development and print media. I enjoy turning complex problems into simple, beautiful and intuitive designs.

My job is to build your website so that it is functional and user-friendly but at the same time attractive. Moreover, I add personal touch to your product and make sure that is eye-catching and easy to use. My aim is to bring across your message and identity in the most creative way. I created web design for many famous brand companies.
"""

# https://ionic.io/ionicons
[social]
facebook = "https://facebook.com/"
twitter = "https://twitter.com/"
instagram = "https://instagram.com/"
github = "https://github.com/ivansaul"


[testimonial]

[testimonial.1]
name = "Daniel Lewis"
avatar = "./config/assets/avatars/avatar-1.png"
text = "Ivan Saul's programming skills are truly impressive. His ability to write clean and efficient code has significantly improved our software projects. Ivan's problem-solving skills and attention to detail have made him an invaluable asset to our team. We highly recommend Ivan for any programming project. He is a talented and dedicated professional."

[testimonial.2]
name = "Jessica Miller"
avatar = "./config/assets/avatars/avatar-2.png"
text = "Ivan Saul is an exceptional programmer with a strong passion for coding. His expertise in various programming languages and frameworks is remarkable. Ivan's ability to translate complex requirements into elegant solutions is unmatched. Working with Ivan has been a pleasure, and his contributions have greatly impacted the success of our projects."

[testimonial.3]
name = "Emily Evans"
avatar = "./config/assets/avatars/avatar-3.png"
text = "Ivan Saul is a highly skilled and innovative programmer. His ability to think outside the box and find creative solutions to complex problems is remarkable. Ivan's attention to detail and commitment to delivering high-quality code have made him an invaluable member of our development team. We are grateful for his contributions and expertise."

[testimonial.4]
name = "Henry William"
avatar = "./config/assets/avatars/avatar-4.png"
text = "Ivan Saul's programming expertise is exceptional. His deep understanding of software development principles and best practices has been instrumental in the success of our projects. Ivan's dedication to writing clean, maintainable, and scalable code sets him apart. We highly recommend Ivan for any programming task; he consistently delivers outstanding results."


# Technology I have woirked with
[technologies]
python = "./config/assets/icons/python.svg"
firebase = "./config/assets/icons/firebase.svg"
flutter = "./config/assets/icons/flutter.svg"
dart = "./config/assets/icons/dart.svg"