############## Education config #################
#################################################
[[education]]
title = "College"
timeline = "2022 — present"
description = "I am currently persuing my UG in Computer Sciences and Engineering"

[[education]]
title = "Higher Secondary Education"
timeline = "2020 — 2022"
description = "I have complted my higher secondary Education at Happy Valley International School, Vijayawada, Andhra Pradesh, India"

[[education]]
title = "Secondary School / Matriculation"
timeline = "2020"
description = "I have complted my Matriculation at Happy Valley International School, Vijayawada, Andhra Pradesh, India."


############## Experience config ################
#################################################



############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Web design"
value = "60%"

[[skill]]
title = "Python"
value = "70%"

[[skill]]
title = "C, C++"
value = "60%"


############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "100%"

[[language]]
title = "Telugu"
value = "100%"

[[language]]
title = "Hindi"
value = "60%"
